; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S -scalarizer -dxil-op-lower -mtriple=dxil-pc-shadermodel6.3-library %s | FileCheck %s

; This test exercises the lowering of the intrinsic @llvm.smul.with.overflow.i32
; to the IMul DXIL op. IMul returns the full 64-bit product split into its low
; and high 32-bit halves, so the overflow bit is synthesized as
; (high != (low >> 31)).

define noundef i32 @test_IMul(i32 noundef %a, i32 noundef %b) {
; CHECK-LABEL: define noundef i32 @test_IMul(
; CHECK-SAME: i32 noundef [[A:%.*]], i32 noundef [[B:%.*]]) {
; CHECK-NEXT:    [[IMUL1:%.*]] = call [[DX_TYPES_TWOI32:%.*]] @[[DX_OP_BINARYWITHTWOOUTS_I32:[a-zA-Z0-9_$\"\\.-]*[a-zA-Z_$\"\\.-][a-zA-Z0-9_$\"\\.-]*]](i32 41, i32 [[A]], i32 [[B]])
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[DX_TYPES_TWOI32]] [[IMUL1]], 0
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[DX_TYPES_TWOI32]] [[IMUL1]], 1
; CHECK-NEXT:    [[TMP3:%.*]] = ashr i32 [[TMP1]], 31
; CHECK-NEXT:    [[TMP4:%.*]] = icmp ne i32 [[TMP2]], [[TMP3]]
; CHECK-NEXT:    [[TMP5:%.*]] = insertvalue { i32, i1 } poison, i32 [[TMP1]], 0
; CHECK-NEXT:    [[TMP6:%.*]] = insertvalue { i32, i1 } [[TMP5]], i1 [[TMP4]], 1
; CHECK-NEXT:    [[PROD:%.*]] = extractvalue { i32, i1 } [[TMP6]], 0
; CHECK-NEXT:    [[OVF:%.*]] = extractvalue { i32, i1 } [[TMP6]], 1
; CHECK-NEXT:    [[OVF_ZEXT:%.*]] = zext i1 [[OVF]] to i32
; CHECK-NEXT:    [[RESULT:%.*]] = add i32 [[PROD]], [[OVF_ZEXT]]
; CHECK-NEXT:    ret i32 [[RESULT]]
;
  %imul = call { i32, i1 } @llvm.smul.with.overflow.i32(i32 %a, i32 %b)
  %prod = extractvalue { i32, i1 } %imul, 0
  %ovf = extractvalue { i32, i1 } %imul, 1
  %ovf_zext = zext i1 %ovf to i32
  %result = add i32 %prod, %ovf_zext
  ret i32 %result
}

define noundef <2 x i32> @test_IMul_vec2(<2 x i32> noundef %a, <2 x i32> noundef %b) {
; CHECK-LABEL: define noundef <2 x i32> @test_IMul_vec2(
; CHECK-SAME: <2 x i32> noundef [[A:%.*]], <2 x i32> noundef [[B:%.*]]) {
; CHECK-NEXT:    [[A_I0:%.*]] = extractelement <2 x i32> [[A]], i64 0
; CHECK-NEXT:    [[B_I0:%.*]] = extractelement <2 x i32> [[B]], i64 0
; CHECK-NEXT:    [[IMUL_I09:%.*]] = call [[DX_TYPES_TWOI32:%.*]] @[[DX_OP_BINARYWITHTWOOUTS_I32]](i32 41, i32 [[A_I0]], i32 [[B_I0]])
; CHECK-NEXT:    [[TMP1:%.*]] = extractvalue [[DX_TYPES_TWOI32]] [[IMUL_I09]], 0
; CHECK-NEXT:    [[TMP2:%.*]] = extractvalue [[DX_TYPES_TWOI32]] [[IMUL_I09]], 1
; CHECK-NEXT:    [[TMP3:%.*]] = ashr i32 [[TMP1]], 31
; CHECK-NEXT:    [[TMP4:%.*]] = icmp ne i32 [[TMP2]], [[TMP3]]
; CHECK-NEXT:    [[TMP5:%.*]] = insertvalue { i32, i1 } poison, i32 [[TMP1]], 0
; CHECK-NEXT:    [[TMP6:%.*]] = insertvalue { i32, i1 } [[TMP5]], i1 [[TMP4]], 1
; CHECK-NEXT:    [[A_I1:%.*]] = extractelement <2 x i32> [[A]], i64 1
; CHECK-NEXT:    [[B_I1:%.*]] = extractelement <2 x i32> [[B]], i64 1
; CHECK-NEXT:    [[IMUL_I18:%.*]] = call [[DX_TYPES_TWOI32]] @[[DX_OP_BINARYWITHTWOOUTS_I32]](i32 41, i32 [[A_I1]], i32 [[B_I1]])
; CHECK-NEXT:    [[TMP7:%.*]] = extractvalue [[DX_TYPES_TWOI32]] [[IMUL_I18]], 0
; CHECK-NEXT:    [[TMP8:%.*]] = extractvalue [[DX_TYPES_TWOI32]] [[IMUL_I18]], 1
; CHECK-NEXT:    [[TMP9:%.*]] = ashr i32 [[TMP7]], 31
; CHECK-NEXT:    [[TMP10:%.*]] = icmp ne i32 [[TMP8]], [[TMP9]]
; CHECK-NEXT:    [[TMP11:%.*]] = insertvalue { i32, i1 } poison, i32 [[TMP7]], 0
; CHECK-NEXT:    [[TMP12:%.*]] = insertvalue { i32, i1 } [[TMP11]], i1 [[TMP10]], 1
; CHECK-NEXT:    [[PROD_ELEM0:%.*]] = extractvalue { i32, i1 } [[TMP6]], 0
; CHECK-NEXT:    [[PROD_ELEM01:%.*]] = extractvalue { i32, i1 } [[TMP12]], 0
; CHECK-NEXT:    [[OVF_ELEM1:%.*]] = extractvalue { i32, i1 } [[TMP6]], 1
; CHECK-NEXT:    [[OVF_ELEM12:%.*]] = extractvalue { i32, i1 } [[TMP12]], 1
; CHECK-NEXT:    [[OVF_ZEXT_I0:%.*]] = zext i1 [[OVF_ELEM1]] to i32
; CHECK-NEXT:    [[OVF_ZEXT_I1:%.*]] = zext i1 [[OVF_ELEM12]] to i32
; CHECK-NEXT:    [[RESULT_I0:%.*]] = add i32 [[PROD_ELEM0]], [[OVF_ZEXT_I0]]
; CHECK-NEXT:    [[RESULT_I1:%.*]] = add i32 [[PROD_ELEM01]], [[OVF_ZEXT_I1]]
; CHECK-NEXT:    [[RESULT_UPTO0:%.*]] = insertelement <2 x i32> poison, i32 [[RESULT_I0]], i64 0
; CHECK-NEXT:    [[RESULT:%.*]] = insertelement <2 x i32> [[RESULT_UPTO0]], i32 [[RESULT_I1]], i64 1
; CHECK-NEXT:    ret <2 x i32> [[RESULT]]
;
  %imul = call { <2 x i32>, <2 x i1> } @llvm.smul.with.overflow.v2i32(<2 x i32> %a, <2 x i32> %b)
  %prod = extractvalue { <2 x i32>, <2 x i1> } %imul, 0
  %ovf = extractvalue { <2 x i32>, <2 x i1> } %imul, 1
  %ovf_zext = zext <2 x i1> %ovf to <2 x i32>
  %result = add <2 x i32> %prod, %ovf_zext
  ret <2 x i32> %result
}

declare { i32, i1 } @llvm.smul.with.overflow.i32(i32, i32)
declare { <2 x i32>, <2 x i1> } @llvm.smul.with.overflow.v2i32(<2 x i32>, <2 x i32>)
